hwData <- read.table("C:/Users/Ryan/Documents/[BIOL230] Bioinformatics Languages (R)/hw01/hw1_data.csv", header=TRUE, sep=",")
cat(names(hwData),"\n")
print(head(hwData, n=2))
print(nrow(hwData))
print(tail(hwData, n=2))
print(hwData[47, "Ozone"])
sum(is.na(hwData["Ozone"]))
print(mean(hwData$Ozone, na.rm = TRUE))
x <- subset(hwData, Ozone > 31 & Temp > 90)
mean(x$Solar.R)
mean(subset(hwData, Month == 6, select=c("Temp"))$Temp)
print(hwData[which.max(subset(hwData, Month == 5)$Ozone), "Ozone"])