source("~/lab05_Castner/lab05_Castner_Ryan.R")
currWD <- getwd()
setwd("~/lab05_Castner")
helaData <- list.files(path="helaData", full.names=T, recursive=FALSE)
results <- lapply(helaData, processFile, window=30)
setwd(currWD)
binResults <- split(results, ceiling(seq_along(results)/200))
binAvgResults <- as.data.frame(mean(binResults))
png("lapply.png")
lineGraph(binAvgResults)
dev.off()
library(parallel)
png("mclapply.png")
parallelResults = mclapply(helaData, processFile, window=61)
dev.off()